---
title: "MIMIC IV - ED Investigation"
output: html_notebook
---

```{r}
library(tidyverse)
library(stringr)
```


```{r}
base_data_path <- "~/DPhil/Projects/EHR-Indication-Processing/99_Sandbox/MIMIC/physionet.org/files/mimic-iv-ed/2.2/ed/"

# Previous Medication
medrecon <- read_csv(paste0(base_data_path, "medrecon.csv"), col_types = cols(
  subject_id = col_double(),
  stay_id = col_double(),
  charttime = col_datetime(format = ""),
  name = col_character(),
  gsn = col_factor(),
  ndc = col_factor(),
  etc_rn = col_double(),
  etccode = col_factor(),
  etcdescription = col_factor()
))

# Medication
phyxis <- read_csv(paste0(base_data_path, "pyxis.csv"), col_types = cols(
  subject_id = col_double(),
  stay_id = col_double(),
  charttime = col_datetime(format = ""),
  med_rn = col_double(),
  name = col_character(),
  gsn_rn = col_double(),
  gsn = col_character()
))

# Triage
triage <- read_csv(paste0(base_data_path, "triage.csv"), col_types = cols(
  subject_id = col_double(),
  stay_id = col_double(),
  temperature = col_double(),
  heartrate = col_double(),
  resprate = col_double(),
  o2sat = col_double(),
  sbp = col_double(),
  dbp = col_double(),
  pain = col_character(),
  acuity = col_double(),
  chiefcomplaint = col_character()
))
```


## Medrecon
```{r}
medrecon %>%
  summary()
```

```{r}
medrecon %>%
  count(etcdescription, sort = T)
```

```{r}
medrecon %>%
  filter(str_detect(etcdescription, "(?i)antibiotic"))
```

## Phyxis
```{r}
phyxis %>% 
  filter(is.na(gsn)) %>%
  count(name, sort=TRUE)
```

